### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by kecorbin** [jonstacks13/mercury#2]
First time i've looked at this project, it's pretty slick!  I had a bit of a problem getting the dependencies mapped right.. not sure if this is an issue here or not, but thought I would let you know. 

Instead of scapy-python3==0.14 i think it should be scapy==2.3.3

working pip freeze
```
appdirs==1.4.0
Django==1.8.4
djangoajax==2.2.15
dnet==1.12
hurry.filesize==0.9
packaging==16.8
pcapy==0.11.1
pyparsing==2.1.10
scapy==2.3.3
six==1.10.0
```

i also had to tweak around with libdnet - brew install didn't work right for me. 
```
cd
git clone https://github.com/dugsong/libdnet.git
cd libdnet
./configure && make
cd python
python setup.py install

```

**Comment by jonstacks** [comment]
Good call, @kecorbin. I wrote this on my linux machine. I'm assuming the libdnet might not be included on mac and the brewed version might be different. I think a good fix would be to create a `Dockerfile` and maybe a `docker-compose.yaml` for some consistency.
